AllCops:
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4

  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "frontend/**/*"

# ref. https://github.com/bbatsov/ruby-style-guide#indent-conditional-assignment
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: keyword
  AutoCorrect: true

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

# e.g. it { expect{ subject }.to change { foo }
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

# Allow variable name starting with "_"
Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - "config/routes.rb"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 24

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/LineLength:
  Max: 120
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*"

# Allow methods starting with "has_"
Naming/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

# Allow Japanese comments
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/MixinUsage:
  Exclude:
    - "bin/setup"
    - "bin/update"

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Prefer trailing comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
